/**============================================================================
Name        : metric_type.hpp
Created on  : 29.08.2026
Author      : Andrei Tokmakov
Version     : 1.0
Copyright   : Your copyright notice
Description : Defines metric types collected by the trading system.
===============================================================================

Overview
--------
This file defines the set of metric types collected by the trading system.

Metrics are used to observe the behaviour, performance, health, and activity
of the trading pipeline without coupling individual components to a concrete
metrics backend.

The metric types are intentionally expressed as high-level events and
measurements corresponding to the main stages of the trading pipeline:

    Market Data
        |
        v
    BookBuilder / OrderBook
        |
        v
    Strategy
        |
        v
    Risk
        |
        v
    Order Management
        |
        v
    Execution Gateway
        |
        v
    Exchange

The enum is not intended to describe individual exchange messages or strategy
specific events. Such details should remain in the corresponding component
data structures.

Metric Categories
-----------------

1. Market Data Metrics
----------------------

MarketDataReceived
    Number of market-data messages received by the trading system.

    This metric represents messages successfully received from the market-data
    source or gateway.

    It can be used to monitor:
        - market-data input rate;
        - message throughput;
        - connectivity health;
        - unexpected drops in incoming traffic.

MarketDataParsed
    Number of market-data messages successfully parsed.

    This metric allows received messages to be distinguished from messages
    that could not be decoded or interpreted.

MarketDataParseErrors
    Number of market-data messages that failed to parse.

    A continuously increasing value may indicate:
        - malformed messages;
        - protocol changes;
        - corrupted data;
        - parser implementation problems.

MarketDataSequenceErrors
    Number of detected market-data sequence errors.

    Sequence errors include gaps, duplicates, or otherwise invalid sequence
    transitions detected while processing incremental market-data updates.

MarketDataSnapshots
    Number of market-data snapshots successfully processed.

    A snapshot normally establishes or restores the initial state of the
    order book before incremental updates are applied.

MarketDataUpdates
    Number of incremental market-data updates successfully processed.

    This metric represents updates that were accepted and applied to the
    current market-data state.


2. Order Book Metrics
---------------------

OrderBookUpdates
    Number of successful order-book updates.

    This represents updates that were validated and successfully applied to
    the OrderBook state.

OrderBookRebuilds
    Number of order-book rebuild operations.

    A rebuild may occur after a sequence gap, recovery procedure, reconnect,
    or other event requiring the current book state to be reconstructed.

OrderBookSequenceErrors
    Number of sequence validation failures detected by the OrderBook.

    The OrderBook is responsible for validating the continuity of market-data
    updates and maintaining a consistent market-data state.


3. Strategy Metrics
-------------------

StrategySignals
    Number of trading signals generated by the strategy.

    A signal represents a strategy decision that may potentially result in
    an order request.

StrategySignalsRejected
    Number of strategy signals rejected before an order request is created.

    Rejection may occur because of strategy-specific conditions or because
    the signal does not satisfy the strategy's own trading rules.


4. Risk Metrics
---------------

RiskChecks
    Number of risk checks performed before an order is submitted.

RiskRejected
    Number of order requests rejected by the risk-management layer.

    Typical reasons include:
        - position limits;
        - maximum order quantity;
        - price limits;
        - notional limits;
        - rate limits;
        - insufficient available risk budget;
        - trading state restrictions.

RiskAccepted
    Number of order requests successfully accepted by the risk-management
    layer and passed to the order-management/execution stage.


5. Order Management Metrics
---------------------------

OrderRequests
    Number of order requests created by the strategy or trading logic.

    This metric represents an intent to send an order and is counted before
    execution-gateway processing.

OrdersSubmitted
    Number of orders successfully submitted to the execution gateway or
    exchange interface.

OrdersRejected
    Number of orders rejected before reaching the exchange.

    This includes rejections caused by local validation, risk checks,
    order-management rules, or execution-gateway constraints.

OrdersCancelled
    Number of successful order cancellation requests.

OrdersAmended
    Number of successful order amendment requests.

OrdersCompleted
    Number of orders that reached a terminal state.

    Depending on the execution model, terminal states may include:
        - fully filled;
        - cancelled;
        - rejected;
        - expired.


6. Execution Metrics
--------------------

ExecutionReports
    Number of execution reports received from the execution gateway.

    An execution report represents an exchange or broker response describing
    an order state transition, acknowledgement, rejection, fill, cancellation,
    or other execution event.

ExecutionAcknowledgements
    Number of execution acknowledgements received.

ExecutionRejects
    Number of execution-level order rejections received.

ExecutionFills
    Number of execution fills received.

    This metric counts fill events rather than total executed quantity.

ExecutionPartiallyFilled
    Number of orders that entered or remained in a partially-filled state.

ExecutionFullyFilled
    Number of orders that became fully filled.

ExecutionCancels
    Number of execution reports confirming order cancellation.

ExecutionErrors
    Number of execution-related errors detected by the execution gateway.


7. Position and Trading State Metrics
-------------------------------------

PositionUpdates
    Number of position-state updates processed by the trading system.

PositionLimitBreaches
    Number of detected position-limit violations.

ExposureLimitBreaches
    Number of detected exposure or notional-limit violations.

TradingHaltEvents
    Number of events that caused trading to be halted or disabled.

TradingResumeEvents
    Number of events that caused trading to resume after a halt.


8. Connectivity and Gateway Metrics
-----------------------------------

GatewayConnections
    Number of successful connections established by a gateway.

GatewayDisconnections
    Number of gateway disconnections detected.

GatewayReconnects
    Number of successful gateway reconnection attempts.

GatewayErrors
    Number of errors reported by a gateway.

These metrics are useful for distinguishing trading-system problems from
external connectivity or exchange-related problems.


9. Performance Metrics
----------------------

The following metric types represent latency or timing measurements.

MarketDataLatency
    Time between receiving a market-data message and completing the relevant
    market-data processing.

OrderBookLatency
    Time required to apply a market-data update to the OrderBook.

StrategyLatency
    Time required for the strategy to process a market event and produce its
    decision.

RiskLatency
    Time required to perform risk validation for an order request.

OrderSubmissionLatency
    Time between creation of an order request and submission to the
    execution gateway.

ExecutionLatency
    Time between order submission and receiving the corresponding execution
    response.

EndToEndLatency
    End-to-end latency between the relevant market-data event and the resulting
    execution-related event.

For latency metrics, the metric type identifies what is being measured.
The actual latency value and timestamp information should be stored separately
from MetricType.


10. Error Metrics
-----------------

Errors
    Number of generic trading-system errors for which no more specific metric
    type exists.

ComponentErrors
    Number of component-level errors.

FatalErrors
    Number of errors that caused a component or the trading system to enter
    an unrecoverable or stopped state.


Design Notes
------------

MetricType represents the semantic identity of a metric. It does not contain
the metric value, timestamp, instrument, exchange, order identifier, or other
dimensions.

For example, a metric record may conceptually contain:

    MetricType
    Timestamp
    Value
    Instrument
    Venue

The exact representation of a metric record is defined elsewhere.

MetricType values should remain stable once they are persisted or exported.
If metrics are stored in recordings, databases, or binary streams, inserting
new enum values in the middle of the enumeration can change their numeric
representation. New metric types should therefore normally be appended before
_Count.

The _Count value represents the number of defined metric types and can be used
for allocating fixed-size metric storage, arrays, or lookup tables.

The enumeration uses uint16_t because the number of metric types is expected
to remain small while an explicitly sized underlying type provides predictable
storage and serialization characteristics.

===============================================================================**/

#ifndef FINANCETECHNOLOGYPROJECTS_METRIC_TYPE_HPP
#define FINANCETECHNOLOGYPROJECTS_METRIC_TYPE_HPP

#include <cstdint>

namespace trading::metrics
{
    enum class MetricType : uint16_t
    {
        // Market Data
        MarketDataReceived,
        MarketDataParsed,
        MarketDataParseErrors,
        MarketDataSequenceErrors,
        MarketDataSnapshots,
        MarketDataUpdates,

        // Order Book
        OrderBookUpdates,
        OrderBookRebuilds,
        OrderBookSequenceErrors,

        // Strategy
        StrategySignals,
        StrategySignalsRejected,

        // Risk
        RiskChecks,
        RiskAccepted,
        RiskRejected,

        // Order Management
        OrderRequests,
        OrdersSubmitted,
        OrdersRejected,
        OrdersCancelled,
        OrdersAmended,
        OrdersCompleted,

        // Execution
        ExecutionReports,
        ExecutionAcknowledgements,
        ExecutionRejects,
        ExecutionFills,
        ExecutionPartiallyFilled,
        ExecutionFullyFilled,
        ExecutionCancels,
        ExecutionErrors,

        // Position / Trading State
        PositionUpdates,
        PositionLimitBreaches,
        ExposureLimitBreaches,
        TradingHaltEvents,
        TradingResumeEvents,

        // Connectivity / Gateways
        GatewayConnections,
        GatewayDisconnections,
        GatewayReconnects,
        GatewayErrors,

        // Performance / Latency
        MarketDataLatency,
        OrderBookLatency,
        StrategyLatency,
        RiskLatency,
        OrderSubmissionLatency,
        ExecutionLatency,
        EndToEndLatency,

        // Errors
        Errors,
        ComponentErrors,
        FatalErrors,

        _Count
    };
}

#endif // FINANCETECHNOLOGYPROJECTS_METRIC_TYPE_HPP